spring:
  application:
    name: discovery-eureka-application-2
server:
  port: 8762
#eureka:
#  instance:
#    hostname: eureka_server_1
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://eureka_server_0:8761/eureka/
#    fetch-registry: false
#    register-with-eureka: false


eureka:
  client:
    service-url:
      defaultZone: http://eureka.server0:8762/eureka/
    fetch-registry: false
    register-with-eureka: false